/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hospital_Management;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author J786N72
 */
public class Add_patient extends javax.swing.JFrame {

    /**
     * Creates new form Add_patient
     */
    public Add_patient() {
        initComponents();
        setSize(850,650);
        setLocation(100,50);
        findId();

    }

    
        
    String idd="30001"; 
       
    public void findId()
    {
        
        int i;
        try
        {
         Connection con;
        Statement stmt;
        ResultSet rs; 
        String host="jdbc:derby://localhost:1527/data_folder";
        String uName="rony";
        String uPass="rony";
         con = DriverManager.getConnection(host,uName,uPass);
        stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        
         String sql="SELECT * FROM RONY.PATIENT_DETAILS";
         rs=stmt.executeQuery(sql);
         
         if(rs.last())
         {
             idd=rs.getString("ID");
             //System.out.println(idd);
             i=Integer.parseInt(idd);
             i++;
             idd=String.valueOf(i); 
            // System.out.println(idd);
         }
         
         
         id.setText(idd);
         
         stmt.close();
         rs.close();
         
        }catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
        
        
    }   
   public void Add()
    {     
        
        try{
            Connection con;
        Statement stmt;
        ResultSet rs; 
            
        String host="jdbc:derby://localhost:1527/data_folder";
        String uName="rony";
        String uPass="rony";
        con = DriverManager.getConnection(host,uName,uPass);
        stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
      
         String sql="SELECT * FROM RONY.PATIENT_DETAILS";
         rs=stmt.executeQuery(sql);
         rs.moveToInsertRow();
         SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
         rs.updateString("ID",idd);
         rs.updateString("FIRST_NAME",firstnm.getText());
         rs.updateString("LAST_NAME",lastnm.getText());
         rs.updateString("AGE",age.getText());
         rs.updateString("SEX",(String)sex.getSelectedItem());
         rs.updateString("ADMIT_DATE",sdf.format(admit.getDate()));
         rs.updateString("MARITAL_STATUS",(String)marit.getSelectedItem());
         rs.updateString("BLOOD_GRP",(String)bloodgrp.getSelectedItem());
         rs.updateString("CONTACT_NUM",contact.getText());
         rs.updateString("BED_NUM",bed.getText());
         rs.updateString("WARD_NO",ward.getText());
         rs.updateString("ADDRESS",address.getText());
         
         rs.insertRow();
         
         stmt.close();
         rs.close();
         
        // id.setText("");
        findId();
         firstnm.setText("");
         lastnm.setText("");
         ward.setText("");
         bed.setText("");
         age.setText("");
         contact.setText("");
         marit.setSelectedItem("Married");
         address.setText("");
         
        
         
        JOptionPane.showMessageDialog(this,"Record has been added","ADD",-1);
        
        
        
    }catch(Exception e)
    {
        System.out.println(e);
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        search = new javax.swing.JButton();
        view = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        home = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        add = new javax.swing.JButton();
        bed = new javax.swing.JTextField();
        firstnm = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        lastnm = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        ward = new javax.swing.JTextField();
        marit = new javax.swing.JComboBox<>();
        sex = new javax.swing.JComboBox<>();
        bloodgrp = new javax.swing.JComboBox<>();
        admit = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        search.setBackground(new java.awt.Color(204, 204, 204));
        search.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        search.setText("Search Patient");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(280, 10, 240, 40);

        view.setBackground(new java.awt.Color(204, 204, 204));
        view.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        view.setText("View Patient");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        getContentPane().add(view);
        view.setBounds(540, 10, 220, 40);

        jButton6.setBackground(new java.awt.Color(153, 153, 153));
        jButton6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton6.setText("Add Patient");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(40, 10, 210, 40);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 60, 760, 0);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 204));
        jSeparator2.setForeground(new java.awt.Color(51, 51, 255));
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(10, 62, 800, 10);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setText("ADD PATIENT");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 80, 400, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Last Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(440, 230, 100, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("ID NO.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 180, 70, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Blood group");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 470, 110, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("First Name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 240, 100, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("Age");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 300, 70, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("Sex");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 360, 70, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText("Marital Status");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 420, 120, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setText("Contact No.");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(440, 350, 100, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 255));
        jLabel11.setText("Admit date");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 530, 140, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 255));
        jLabel12.setText("Address");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(440, 290, 70, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 255));
        jLabel13.setText("Ward No.");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(440, 410, 90, 40);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 255));
        jLabel14.setText("Bed No.");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(440, 470, 70, 40);

        logout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(0, 0, 255));
        logout.setText("LogOut");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout);
        logout.setBounds(670, 80, 120, 40);

        home.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        home.setForeground(new java.awt.Color(0, 0, 255));
        home.setText("HOME");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home);
        home.setBounds(550, 80, 110, 40);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hospital_Management/text.jpg"))); // NOI18N
        jLabel15.setText("jLabel15");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(10, 70, 800, 70);

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 0, 255));
        jButton9.setText("LogOut");
        getContentPane().add(jButton9);
        jButton9.setBounds(670, 80, 120, 40);

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(0, 0, 255));
        jButton10.setText("LogOut");
        getContentPane().add(jButton10);
        jButton10.setBounds(670, 80, 120, 40);

        add.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add.setForeground(new java.awt.Color(0, 0, 255));
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add);
        add.setBounds(610, 160, 160, 40);

        bed.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        bed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(bed);
        bed.setBounds(600, 480, 190, 30);

        firstnm.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        firstnm.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(firstnm);
        firstnm.setBounds(180, 240, 190, 30);

        age.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        age.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(age);
        age.setBounds(180, 300, 190, 30);

        id.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(id);
        id.setBounds(180, 180, 190, 30);

        lastnm.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lastnm.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(lastnm);
        lastnm.setBounds(600, 230, 190, 30);

        address.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        address.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(address);
        address.setBounds(600, 290, 190, 30);

        contact.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        contact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(contact);
        contact.setBounds(600, 350, 190, 30);

        ward.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        ward.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(ward);
        ward.setBounds(600, 420, 190, 30);

        marit.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        marit.setMaximumRowCount(2);
        marit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Married", "Unmarried" }));
        getContentPane().add(marit);
        marit.setBounds(180, 420, 190, 30);

        sex.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        sex.setMaximumRowCount(2);
        sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        getContentPane().add(sex);
        sex.setBounds(180, 360, 190, 30);

        bloodgrp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A(+)ve", "A(-)ve", "B(+)ve", "B(-)ve", "AB(+)ve", "AB(-)ve", "O(+)ve", "O(-)ve" }));
        getContentPane().add(bloodgrp);
        bloodgrp.setBounds(180, 480, 190, 30);
        getContentPane().add(admit);
        admit.setBounds(180, 532, 190, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        Receptionist_home receptionist_home=new Receptionist_home();
        receptionist_home.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_homeActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        Admin_home admin_home=new Admin_home();
        admin_home.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        Search_patient search_patient=new Search_patient();
        search_patient.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        
        // TODO add your handling code here:
        Patient_table ptable=new Patient_table();
        ptable.setVisible(true);
    }//GEN-LAST:event_viewActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        Add();
    }//GEN-LAST:event_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_patient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField address;
    private com.toedter.calendar.JDateChooser admit;
    private javax.swing.JTextField age;
    private javax.swing.JTextField bed;
    private javax.swing.JComboBox<String> bloodgrp;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField firstnm;
    private javax.swing.JButton home;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField lastnm;
    private javax.swing.JButton logout;
    private javax.swing.JComboBox<String> marit;
    private javax.swing.JButton search;
    private javax.swing.JComboBox<String> sex;
    private javax.swing.JButton view;
    private javax.swing.JTextField ward;
    // End of variables declaration//GEN-END:variables
}
