/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hospital_Management;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import static Hospital_Management.logInInfo.doctorId;
import static Hospital_Management.logInInfo.doctorPass;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class appointment_list extends javax.swing.JFrame {

    /**
     * Creates new form Patient_table
     */
    public appointment_list() {
        initComponents();
        
        setSize(850,650);
        setLocation(100,50);
    }
    void show_data()
    {
        Connection con;
        Statement stmt;
        ResultSet rs;
        try{
            
        String host="jdbc:derby://localhost:1527/data_folder";
        String uName="rony";
        String uPass="rony";
        con = DriverManager.getConnection(host,uName,uPass);
        
        stmt=con.createStatement();
        //String ID=id.getText();
        String name=doctorId;
        String pass=doctorPass;
        String sql="SELECT * FROM RONY.DOCTOR_LOGIN WHERE USERNAME='"+name+"' AND PASSWORD='"+pass+"'";
         rs=stmt.executeQuery(sql);
         rs.next();
       String ID=rs.getString("ID");
            //System.out.println("id  : "+doctorId);
            stmt.close();
            rs.close();  
         stmt=con.createStatement();
         SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
         sql="SELECT * FROM RONY.APPIONTMENT WHERE DOCTOR_ID='"+ID+"' AND DATE='"+sdf.format(date.getDate())+"'";
         rs=stmt.executeQuery(sql);
         DefaultTableModel model1=(DefaultTableModel)pTable.getModel();
         int a=1;
         while(rs.next())
         {
             model1.addRow(new Object[]{a++,rs.getString("FIRST_NAME")+" "+rs.getString("LAST_NAME"),rs.getString("SEX"),rs.getString("AGE"),rs.getString("CONTACT"),rs.getString("ADDRESS")});
         }
         if(a==1)
         {
             JOptionPane.showMessageDialog(this,"No Patient to view","Message",0);
         }
        
        
    }catch(Exception e)
    {
        System.out.println(e.getMessage());
    }
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pTable = new javax.swing.JTable();
        search = new javax.swing.JButton();
        date = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        pTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial No.", "Name", "Sex", "Age", "Contact No.", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(pTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 70, 830, 640);

        search.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        search.setForeground(new java.awt.Color(0, 0, 204));
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(320, 20, 180, 40);
        getContentPane().add(date);
        date.setBounds(90, 20, 190, 40);

        jLabel2.setText("Enter Date :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 0, 120, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        show_data();
    }//GEN-LAST:event_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(appointment_list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(appointment_list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(appointment_list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(appointment_list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new appointment_list().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable pTable;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}
