/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hospital_Management;

import static Hospital_Management.logInInfo.adminPass;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author J786N72
 */
public class Change_password_admin extends javax.swing.JFrame {

    /**
     * Creates new form Change_password
     */
    public Change_password_admin() {
        initComponents();
        setSize(450,270);
        setLocation(290,290);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        neww = new javax.swing.JPasswordField();
        confrm = new javax.swing.JPasswordField();
        old = new javax.swing.JPasswordField();
        ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 21)); // NOI18N
        jLabel1.setText("New Password");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 70, 210, 50);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 21)); // NOI18N
        jLabel2.setText("Confarm Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 120, 210, 50);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 21)); // NOI18N
        jLabel3.setText("Old Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 10, 210, 50);

        neww.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        neww.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(neww);
        neww.setBounds(220, 70, 190, 40);

        confrm.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        confrm.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(confrm);
        confrm.setBounds(220, 130, 190, 40);

        old.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        old.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(old);
        old.setBounds(220, 10, 190, 40);

        ok.setBackground(new java.awt.Color(153, 153, 153));
        ok.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ok.setForeground(new java.awt.Color(51, 0, 153));
        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        getContentPane().add(ok);
        ok.setBounds(280, 190, 70, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed

        Connection con;
        Statement stmt;
        ResultSet rs;
        String usrnm=old.getText();
        String usrpass=neww.getText();
        String conf=confrm.getText();
        
        
        try{
        String host="jdbc:derby://localhost:1527/data_folder";
        String uName="rony";
        String uPass="rony";
        con = DriverManager.getConnection(host,uName,uPass);
        stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
      
         String sql="SELECT * FROM RONY.ADMIN_LOGIN WHERE PASSWORD='"+usrnm+"'";
         rs=stmt.executeQuery(sql);
         
         if(usrnm.equals(adminPass) && rs.next())
         {
             if(usrpass.equals(conf))
             {
                 adminPass=usrpass;
                 rs.updateString("PASSWORD", usrpass);
                 rs.updateRow();
                 JOptionPane.showMessageDialog(this, "Password change successfull!!!!" , "Message", -1);
                  
                 dispose();
             }
             else
             {
                 JOptionPane.showMessageDialog(this, "password is incorrect!!!!" , "Message", JOptionPane.ERROR_MESSAGE);
             }
                       
         }
         else
         {
             JOptionPane.showMessageDialog(this, "password is invalid!!!!" , "Message", JOptionPane.ERROR_MESSAGE);
         }
         stmt.close();
         rs.close();
        
        
    }catch(Exception e)
    {
        System.out.println(e.getMessage());
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_okActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        JFrame frame=new JFrame("Change Password");
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Change_password_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Change_password_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Change_password_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Change_password_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Change_password_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confrm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField neww;
    private javax.swing.JButton ok;
    private javax.swing.JPasswordField old;
    // End of variables declaration//GEN-END:variables
}
