/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Hospital_Management;

/**
 *
 * @author J786N72
 */
public class Doctor_home extends javax.swing.JFrame {

    /** Creates new form Receptionist_home */
    public Doctor_home() {
        initComponents();
        setSize(850,650);
        setLocation(100,50);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        appointment = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        passchange = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("Profile");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DOCTOR PORTAL");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 120, 390, 70);

        logout.setBackground(new java.awt.Color(204, 204, 204));
        logout.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        logout.setForeground(new java.awt.Color(0, 0, 255));
        logout.setText("LogOut");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout);
        logout.setBounds(300, 400, 210, 60);

        appointment.setBackground(new java.awt.Color(204, 204, 204));
        appointment.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        appointment.setForeground(new java.awt.Color(0, 0, 255));
        appointment.setText("Appointments list");
        appointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointmentActionPerformed(evt);
            }
        });
        getContentPane().add(appointment);
        appointment.setBounds(300, 220, 210, 60);

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 255));
        jButton5.setText("Doctor Details");
        getContentPane().add(jButton5);
        jButton5.setBounds(300, 220, 210, 60);

        passchange.setBackground(new java.awt.Color(204, 204, 204));
        passchange.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        passchange.setForeground(new java.awt.Color(0, 0, 255));
        passchange.setText("Change Password");
        passchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passchangeActionPerformed(evt);
            }
        });
        getContentPane().add(passchange);
        passchange.setBounds(300, 310, 210, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hospital_Management/text.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 110, 420, 90);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hospital_Management/Receptionist_home_image.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 830, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        Login_Home login_home=new Login_Home();
        login_home.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void passchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passchangeActionPerformed
        Change_password_doctor change_password=new Change_password_doctor();
        change_password.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_passchangeActionPerformed

    private void appointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointmentActionPerformed
        // TODO add your handling code here:
        appointment_list applist=new appointment_list();
        applist.setVisible(true);
    }//GEN-LAST:event_appointmentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor_home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appointment;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton logout;
    private javax.swing.JButton passchange;
    // End of variables declaration//GEN-END:variables

}
