
package Hospital_Management;

import static Hospital_Management.Admin_login.is;
import static Hospital_Management.Admin_login.os;
import java.awt.event.*;
import java.awt.*;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;

/**
 
 * @author J786N72
 */
public class Login_Home extends javax.swing.JFrame {

    /**
     * Creates new form Login_Home
     */
    public Login_Home() {
        initComponents();
        initComponents();
        setSize(850,650);
        setLocation(100,50);
        //setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        receptionlogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        doctorlogin = new javax.swing.JButton();
        adminlogin = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        doctorlogin1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hospital Management System");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(40, 20, 760, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hospital_Management/text.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 20, 780, 90);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Log In As : ");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 170, 130, 30);

        receptionlogin.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        receptionlogin.setForeground(new java.awt.Color(0, 0, 255));
        receptionlogin.setText("RECEPTIONIST");
        receptionlogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        receptionlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptionloginActionPerformed(evt);
            }
        });
        jPanel2.add(receptionlogin);
        receptionlogin.setBounds(310, 470, 210, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hospital_Management/Doctor.png"))); // NOI18N
        jLabel4.setText("RECEPTIONIST");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(560, 250, 200, 200);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hospital_Management/Admin.png"))); // NOI18N
        jLabel6.setText("ADMIN");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(70, 250, 200, 200);

        doctorlogin.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        doctorlogin.setForeground(new java.awt.Color(0, 0, 255));
        doctorlogin.setText("DOCTOR");
        doctorlogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        doctorlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorloginActionPerformed(evt);
            }
        });
        jPanel2.add(doctorlogin);
        doctorlogin.setBounds(560, 470, 190, 50);

        adminlogin.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        adminlogin.setForeground(new java.awt.Color(0, 0, 255));
        adminlogin.setText("ADMIN");
        adminlogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        adminlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminloginActionPerformed(evt);
            }
        });
        jPanel2.add(adminlogin);
        adminlogin.setBounds(70, 470, 200, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hospital_Management/receptionist.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(310, 250, 200, 200);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hospital_Management/Under_login_as.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 160, 140, 50);

        doctorlogin1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        doctorlogin1.setForeground(new java.awt.Color(0, 0, 255));
        doctorlogin1.setText("DOCTOR");
        doctorlogin1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        doctorlogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorlogin1ActionPerformed(evt);
            }
        });
        jPanel2.add(doctorlogin1);
        doctorlogin1.setBounds(560, 470, 190, 50);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 204));
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(690, 130, 110, 50);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hospital_Management/Homeee.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(-760, -410, 1790, 1020);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1046, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminloginActionPerformed
        // TODO add your handling code here:
        Admin_login addlog=new Admin_login();
        addlog.setVisible(true);
        dispose();
    }//GEN-LAST:event_adminloginActionPerformed

    private void receptionloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptionloginActionPerformed
        // TODO add your handling code here:
        Receptionist_login recptionlog=new Receptionist_login();
        recptionlog.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_receptionloginActionPerformed

    private void doctorloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorloginActionPerformed
        // TODO add your handling code here:
        
        
        Doctor_login doctorlog=new Doctor_login();
        doctorlog.setVisible(true);
        dispose();
    }//GEN-LAST:event_doctorloginActionPerformed

    private void doctorlogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorlogin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorlogin1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        
        Socket client=new Socket("127.0.0.1",3222);
        is=new DataInputStream(client.getInputStream());
        os=new DataOutputStream(client.getOutputStream());
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminlogin;
    private javax.swing.JButton doctorlogin;
    private javax.swing.JButton doctorlogin1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton receptionlogin;
    // End of variables declaration//GEN-END:variables
}
